### ISSUE TITLE
Cannot compile on OSX 10.14 - clang 11

### ISSUE THREAD

**Issue by guillep** [usi-verification-and-security/opensmt#391]
```bash
$ cmake -S opensmt -B build
$ cmake --build build
```

# Error
I have many `ISO C++17 does not allow 'register' storage class specifier` errors in target smtsolvers
```bash
[ 53%] Built target smtsolvers
[ 54%] Building CXX object src/parsers/smt2new/CMakeFiles/parsers.dir/smt2newcontext.cc.o
[ 54%] Building CXX object src/parsers/smt2new/CMakeFiles/parsers.dir/smt2newparser.cc.o
[ 55%] Building CXX object src/parsers/smt2new/CMakeFiles/parsers.dir/smt2newlexer.cc.o
/Users/guille/Projects/smts/opensmt-tests/build/src/parsers/smt2new/smt2newlexer.cc:1081:2: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
        register yy_state_type yy_current_state;
        ^~~~~~~~~
```

# My setup

OSX 10.14

clang:
```bash
$ clang --version
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by aehyvari** [comment]
Hi Guille, you need to upgrade your flex and bison to a more recent version
most likely.

**Comment by guillep** [comment]
Thanks! I already updated bison (because CMake complained about it), but it did not complain about my flex version.
I'll check and come back! Thanks!

**Comment by guillep** [comment]
I confirm I got past that error updating Flex to 2.6.x.

Would a check like the following in `src/parsers/smt2new/CMakeLists.txt` file be welcome as a PR?

```diff
add_library(parsers OBJECT "")

find_package(BISON 3.0 REQUIRED)
- find_package(FLEX REQUIRED)
+ find_package(FLEX 2.6 REQUIRED)
```

**Comment by aehyvari** [comment]
Great to hear! Yes, thanks!

**Comment by blishko** [comment]
@guillep , do you want to create the PR or should we do it? 
Since we switched to C++17, we need to require Flex 2.6 now.

**Comment by guillep** [comment]
I'd gladly do it ;)

https://github.com/usi-verification-and-security/opensmt/pull/392

**Comment by blishko** [comment]
Fixed in #392.
